POST http://localhost:8081/users/friends/send-request?targetUserId=localhost:8081/users/friends/send-request?targetUserId=id7
###
GET http://localhost:8081/users/accounts/profiles/id0
###
POST http://localhost:8081/create/

POST http://localhost:8081/storing/123/321/file?abs
###
GET http://localhost:8081/photos/sorting/photo-ids/?trophyID=trophy3&order=time
###
GET http://localhost:8081/photos/storing/id5

###
POST http://localhost:8081/photos/storing/trophy3/id7
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="1.png"
Content-Type: image/png

< ./ab.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
GET http://localhost:8081/photos/storing/trophy3-id7-1657409128402-812489040.png

###
GET http://localhost:8081/photos/sorting/photoIDs/?userID=id7

###
PUT http://localhost:8081/photos/managing/likes/?userID=id7&picID=trophy3-id7-1657410040725-745958255.png