name: Back-end Actions
on: [push]
jobs:
  Run-Backend-Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - run: echo "repository is ${{ github.repository }}"
      - run: echo "Triggered by a ${{ github.event_name }}"
      - run: echo "Running on ${{ runner.os }}"
      - run: echo "Branch is ${{ github.ref }}"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Instal dependencies
        run: npm ci
      - name: Run tests
        run: npm test
