name: Back-end Actions
on: [push]
jobs:
  Run-Backend-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - run: echo "repository is ${{ github.repository }}"
      - run: echo "Triggered by a ${{ github.event_name }}"
      - run: echo "Running on ${{ runner.os }}"
      - run: echo "Branch is ${{ github.ref }}"
      - name: Load backend secrets
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "${{ github.workspace }}/backend/firebase-service-account.json"
          echo 'GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}' > "${{ github.workspace }}/backend/.env"
          echo 'CLIENT_ID=${{ secrets.SERVER_CLIENT_ID }}' > "${{ github.workspace }}/backend/.env"
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Instal dependencies
        run: npm ci
      - name: Run tests
        run: npm test
